name: Build VNDS-LOVE
on:
    push:
        branches:
            - main
        paths-ignore:
            - "*.md"
            - .github/dependabot.yml
    workflow_dispatch: null
jobs:
    build:
        permissions:
            contents: write
        name: Build for iOS
        runs-on: macos-latest
        steps:
            - name: Install lua
              run: brew install luarocks zip libzip
            - uses: actions/checkout@v4
              with:
                  path: VNDS-LOVE
            - uses: actions/checkout@v4
              with:
                  repository: love2d/love
                  path: love
                  ref: main
            - uses: actions/checkout@v4
              with:
                  repository: love2d/love-apple-dependencies
                  path: deps
                  ref: main
            - name: Copy LOVE dependencies
              run: |
                  cd deps
                  cp -rv iOS/libraries ../love/platform/xcode/ios 
                  cp -rv shared ../love/platform/xcode
                  cd ..
                  cp -rv VNDS-LOVE/xcode/vnds.xcodeproj love/platform/xcode/
                  cp -v VNDS-LOVE/xcode/love-ios.plist love/platform/xcode/ios
                  cp -rv VNDS-LOVE/xcode/Images.xcassets love/platform/xcode/
            - name: Install VNDS dependencies
              run: |
                  luarocks install moonscript
                  luarocks install busted
                  luarocks install alfons
                  luarocks install love-release
            - name: Build VNDS
              working-directory: ./VNDS-LOVE
              run: |
                  make build
            - name: Build ipa
              working-directory: ./love/platform/xcode
              run: |
                  ls
                  xcodebuild -showBuildSettings -project vnds.xcodeproj -scheme love-ios | grep MARKETING_VERSION | tr -d 'MARKETING_VERSION =' > ../../../VNDS-LOVE/app_version.txt
                  xcodebuild -list -project vnds.xcodeproj

                  xcodebuild -project vnds.xcodeproj clean archive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" -sdk iphoneos -destination 'generic/platform=iOS' -archivePath ./arc -scheme love-ios

                  mkdir Payload

                  cp -rv arc.xcarchive/Products/Applications/VNDS.app Payload

                  zip -r VNDS.ipa Payload

            - name: Create AltStore/SideStore/ESign repository
              working-directory: ./VNDS-LOVE
              run: |
                  node create_altstore_repo.mjs
                  export APP_VER=$(cat app_version.txt)
            - name: Archive build artifacts
              uses: actions/upload-artifact@v4
              with:
                  path: |
                      VNDS-LOVE/altStoreManifest.json
                      love/platform/xcode/VNDS.ipa
            - name: Draft Release
              uses: softprops/action-gh-release@v2
              with:
                  draft: true
                  tag_name: "${{ env.APP_VER }}"
                  files: |
                      love/platform/xcode/VNDS.ipa
                      VNDS-LOVE/altStoreManifest.json
